import ContentEditor from '@/components/content/ContentEditor';
import { createContent } from '@pan/shared';
import { revalidatePath } from 'next/cache';

export default function CreateContentPage() {
  const handleSave = async (data: any) => {
    'use server';
    // Remove empty slugs so they get autogenerated or handle properly
    if (!data.slug || data.slug.trim() === '') {
      const title = data.title?.fr || data.title?.en || data.title?.ar || 'article';
      const baseSlug = title.toString().toLowerCase().trim()
        .normalize("NFD").replace(/[\u0300-\u036f]/g, "") // remove accents
        .replace(/\s+/g, '-')
        .replace(/[^\w\-]+/g, '')
        .replace(/\-\-+/g, '-')
        .replace(/^-+/, '')
        .replace(/-+$/, '');
      data.slug = baseSlug + '-' + Math.random().toString(36).substr(2, 4); // add small random to ensure uniqueness
    }
    
    // Fallback author for demo
    data.authorId = 'usr-001';
    data.publishedAt = data.publishedAt ? new Date(data.publishedAt).toISOString() : new Date().toISOString();
    
    await createContent(data);
    revalidatePath('/contents');
  };

  return <ContentEditor onSave={handleSave} />;
}
