import ContentEditor from '@/components/content/ContentEditor';
import { createContent } from '@pan/shared';
import { revalidatePath } from 'next/cache';

export default function CreateContentPage() {
  const handleSave = async (data: any) => {
    'use server';
    // Remove empty slugs so they get autogenerated or handle properly
    if (!data.slug || data.slug.trim() === '') {
      data.slug = 'art-' + Math.random().toString(36).substr(2, 9);
    }
    
    // Fallback author for demo
    data.authorId = 'usr-001';
    data.publishedAt = data.publishedAt ? new Date(data.publishedAt).toISOString() : new Date().toISOString();
    
    await createContent(data);
    revalidatePath('/contents');
  };

  return <ContentEditor onSave={handleSave} />;
}
